name: fluent_gesture
description: Customizing gesture for Precision TouchPad.
publish_to: none
version: 0.0.1
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  fluent_ui: ^4.16.1
  flutter:
    sdk: flutter
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
